export const ARCHETYPES = Object.freeze([
  {
    id: 'resilient-housing',
    label: 'Climate-resilient housing',
    shortLabel: 'Resilient housing',
    description: 'Passive, electrified homes designed for heat, smoke, storms, and grid outages.',
    defaults: {
      capex: 25_000_000,
      annualRevenue: 3_800_000,
      annualOpex: 1_100_000,
      incentives: 1_500_000,
      horizonYears: 25,
      discountRate: 0.08,
      salvageValue: 8_000_000,
      annualEnergyMWh: 7_000,
    },
  },
  {
    id: 'mixed-use',
    label: 'Live-work-play district',
    shortLabel: 'Mixed-use district',
    description: 'Walkable housing, workspaces, local services, and resilient shared infrastructure.',
    defaults: {
      capex: 85_000_000,
      annualRevenue: 12_000_000,
      annualOpex: 4_000_000,
      incentives: 5_000_000,
      horizonYears: 30,
      discountRate: 0.085,
      salvageValue: 28_000_000,
      annualEnergyMWh: 24_000,
    },
  },
  {
    id: 'microgrid',
    label: 'Renewable microgrid',
    shortLabel: 'Microgrid',
    description: 'Solar, wind, controllable loads, and storage sized for savings and outage resilience.',
    defaults: {
      capex: 18_000_000,
      annualRevenue: 3_100_000,
      annualOpex: 650_000,
      incentives: 4_000_000,
      horizonYears: 25,
      discountRate: 0.075,
      salvageValue: 2_000_000,
      annualEnergyMWh: 19_500,
    },
  },
  {
    id: 'small-data-center',
    label: 'Small-scale data center',
    shortLabel: 'Data center',
    description: 'A 5 to 20 MW compute campus screened for power, cooling, fiber, water, and resilience.',
    defaults: {
      capex: 45_000_000,
      annualRevenue: 11_200_000,
      annualOpex: 6_500_000,
      incentives: 3_000_000,
      horizonYears: 15,
      discountRate: 0.1,
      salvageValue: 9_000_000,
      annualEnergyMWh: 95_000,
    },
  },
  {
    id: 'geothermal-district',
    label: 'Geothermal district energy',
    shortLabel: 'Geothermal district',
    description: 'Ground-source or deep geothermal heating, cooling, and power for a connected district.',
    defaults: {
      capex: 32_000_000,
      annualRevenue: 5_800_000,
      annualOpex: 1_200_000,
      incentives: 7_000_000,
      horizonYears: 30,
      discountRate: 0.08,
      salvageValue: 6_000_000,
      annualEnergyMWh: 34_000,
    },
  },
  {
    id: 'hybrid-storage',
    label: 'Hybrid renewables and long-duration storage',
    shortLabel: 'Hybrid storage',
    description: 'Solar and wind paired with iron-air, sodium-ion, or other long-duration storage.',
    defaults: {
      capex: 60_000_000,
      annualRevenue: 10_500_000,
      annualOpex: 2_400_000,
      incentives: 10_000_000,
      horizonYears: 25,
      discountRate: 0.09,
      salvageValue: 7_500_000,
      annualEnergyMWh: 78_000,
    },
  },
]);

export const METRIC_DEFINITIONS = Object.freeze({
  npv: {
    label: 'Net present value',
    short: 'Today\'s value of future project cash flows after the initial investment.',
    detail: 'Future annual cash flow and final salvage value are discounted to today, then the incentive-adjusted initial investment is subtracted.',
  },
  irr: {
    label: 'Internal rate of return',
    short: 'The annual discount rate at which the project\'s net present value equals zero.',
    detail: 'A higher IRR can indicate a stronger return, but it should be compared with project risk, financing costs, and alternative uses of capital.',
  },
  payback: {
    label: 'Simple payback',
    short: 'Estimated years for annual net cash flow to recover the initial investment.',
    detail: 'Simple payback does not discount future cash flows and does not measure value after the payback date.',
  },
  roi: {
    label: 'Undiscounted ROI',
    short: 'Total lifetime net cash return divided by the initial investment.',
    detail: 'This screening metric includes salvage value but does not account for the timing of cash flows.',
  },
  lcoe: {
    label: 'Levelized cost of energy',
    short: 'Average discounted project cost for each megawatt-hour produced or served.',
    detail: 'The model divides discounted incentive-adjusted capital and operating costs by discounted lifetime energy.',
  },
  confidence: {
    label: 'Evidence confidence',
    short: 'How complete, current, and location-specific the supporting data is.',
    detail: 'Live local observations score higher than regional models, cached snapshots, or assumptions entered by a user.',
  },
});

export const SOURCE_CATALOG = Object.freeze([
  { id: 'osm', name: 'OpenStreetMap', url: 'https://www.openstreetmap.org/', category: 'Basemap and context', coverage: 'Global', cadence: 'Continuously updated', status: 'live' },
  { id: 'power', name: 'NASA POWER', url: 'https://power.larc.nasa.gov/', category: 'Solar and climate normals', coverage: 'Global', cadence: 'Near real time and climatology', status: 'live' },
  { id: 'open-meteo', name: 'Open-Meteo', url: 'https://open-meteo.com/', category: 'Weather forecast', coverage: 'Global', cadence: 'Hourly', status: 'live' },
  { id: 'pvwatts', name: 'NREL PVWatts', url: 'https://developer.nrel.gov/docs/solar/pvwatts/v8/', category: 'Solar production model', coverage: 'Global with dataset limits', cadence: 'On request', status: 'live' },
  { id: 'reopt', name: 'NREL REopt', url: 'https://www.nrel.gov/reopt/', category: 'Distributed energy optimization', coverage: 'United States first', cadence: 'On request', status: 'modeled' },
  { id: 'atb', name: 'NREL Annual Technology Baseline', url: 'https://atb.nrel.gov/', category: 'Technology cost and performance assumptions', coverage: 'United States', cadence: 'Annual', status: 'modeled' },
  { id: 'eia', name: 'US EIA', url: 'https://www.eia.gov/opendata/', category: 'Electricity prices and grid operations', coverage: 'United States', cadence: 'Monthly and hourly', status: 'cached' },
  { id: 'irs-48e', name: 'IRS Clean Electricity Investment Credit', url: 'https://www.irs.gov/credits-deductions/clean-electricity-investment-credit', category: 'Federal Section 48E credit and bonus rules', coverage: 'United States', cadence: 'Federal guidance updates', status: 'cached' },
  { id: 'dsire', name: 'DSIRE', url: 'https://dsireusa.org/', category: 'State, local, and utility incentives', coverage: 'United States', cadence: 'Policy updates', status: 'cached' },
  { id: 'gdr', name: 'NREL Geothermal Data Repository', url: 'https://gdr.openei.org/', category: 'Geothermal resource evidence', coverage: 'United States first', cadence: 'Dataset releases', status: 'modeled' },
  { id: 'wind', name: 'NREL WIND Toolkit', url: 'https://www.nrel.gov/gis/wind-resource-maps', category: 'Wind resource potential', coverage: 'United States and selected regions', cadence: 'Dataset releases', status: 'modeled' },
  { id: 'hydro', name: 'NREL water power data and tools', url: 'https://www.nrel.gov/water/data-tools.html', category: 'Hydropower potential', coverage: 'United States', cadence: 'Dataset releases', status: 'modeled' },
  { id: 'hazards', name: 'FEMA, NOAA, and USGS', url: 'https://hazards.fema.gov/nri/', category: 'Flood, fire, heat, storm, and seismic risk', coverage: 'United States', cadence: 'Varies by source', status: 'cached' },
]);
