export const DEMO_SITES = Object.freeze({
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [-119.8138, 39.5296] },
      properties: {
        id: 'reno',
        rank: 1,
        name: 'Reno-Tahoe, NV',
        subtitle: 'Washoe County · Nevada · United States',
        detail: 'Solar · geothermal · data center',
        overall: 82,
        resource: 88,
        infrastructure: 78,
        climate: 74,
        policy: 86,
        confidence: 84,
        solar: 91,
        geothermal: 86,
        hydro: 42,
        wind: 61,
        storage: 84,
        hazards: 58,
        grid: 78,
        energyPrice: 11.2,
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [-78.8784, 42.8864] },
      properties: {
        id: 'buffalo',
        rank: 2,
        name: 'Buffalo-Niagara, NY',
        subtitle: 'Erie County · New York · United States',
        detail: 'Hydro · cooling · mixed-use',
        overall: 79,
        resource: 80,
        infrastructure: 78,
        climate: 76,
        policy: 78,
        confidence: 84,
        solar: 53,
        geothermal: 57,
        hydro: 96,
        wind: 73,
        storage: 75,
        hazards: 38,
        grid: 88,
        energyPrice: 19.3,
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [-104.6091, 38.2544] },
      properties: {
        id: 'pueblo',
        rank: 3,
        name: 'Pueblo, CO',
        subtitle: 'Pueblo County · Colorado · United States',
        detail: 'Solar · wind · storage',
        overall: 77,
        resource: 91,
        infrastructure: 68,
        climate: 71,
        policy: 76,
        confidence: 71,
        solar: 94,
        geothermal: 63,
        hydro: 38,
        wind: 87,
        storage: 91,
        hazards: 52,
        grid: 72,
        energyPrice: 14.1,
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [-79.9414, 37.2709] },
      properties: {
        id: 'roanoke',
        rank: 4,
        name: 'Roanoke, VA',
        subtitle: 'Roanoke Valley · Virginia · United States',
        detail: 'Housing · grid · resilience',
        overall: 74,
        resource: 69,
        infrastructure: 78,
        climate: 82,
        policy: 71,
        confidence: 67,
        solar: 70,
        geothermal: 64,
        hydro: 72,
        wind: 54,
        storage: 72,
        hazards: 34,
        grid: 82,
        energyPrice: 13.4,
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [-21.9426, 64.0049] },
      properties: {
        id: 'reykjanes',
        rank: 5,
        name: 'Reykjanes, Iceland',
        subtitle: 'Southern Peninsula · Iceland',
        detail: 'Geothermal · data center · resilience',
        overall: 73,
        resource: 94,
        infrastructure: 66,
        climate: 78,
        policy: 50,
        confidence: 52,
        solar: 37,
        geothermal: 99,
        hydro: 82,
        wind: 92,
        storage: 68,
        hazards: 66,
        grid: 79,
        energyPrice: 0,
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [36.8219, -1.2921] },
      properties: {
        id: 'nairobi',
        rank: 6,
        name: 'Nairobi-Kajiado, Kenya',
        subtitle: 'Nairobi metropolitan region · Kenya',
        detail: 'Solar · geothermal · mixed-use',
        overall: 68,
        resource: 92,
        infrastructure: 50,
        climate: 72,
        policy: 61,
        confidence: 44,
        solar: 90,
        geothermal: 92,
        hydro: 51,
        wind: 66,
        storage: 79,
        hazards: 46,
        grid: 56,
        energyPrice: 0,
      },
    },
  ],
});
